### ISSUE TITLE
Question: File units

### ISSUE THREAD

**Issue by knockDOUGH** [itsjonlebron/Backbone-One-iPad-Mini-Upgrade#1]
Hello, thanks for putting this together, it's really helpful!

I'm trying to get the stl files printed on https://craftcloud3d.com/material and something they want is the file unit (mm, cm, or in). 

Thanks in advance!

**Comment by evlev06** [comment]
MM - I used JawsTec...Was ~$10 shipped.

**Comment by knockDOUGH** [comment]
thank you!

**Comment by jonochocki** [comment]
Really appreciate you @evlev06 for helping out. Thanks for the heads-up, @knockDOUGH. I'll include the (mm) on the main file to avoid further confusion.
