### ISSUE TITLE
Completed Build

### ISSUE THREAD

**Issue by DRA6N** [itsjonlebron/Backbone-One-iPad-Mini-Upgrade#3]
I printed out the parts you provided. Your instructions were very clear and easy to follow - props for all the images.
I found a pack of 5" ribbon cables that match the ones the backbone uses. This allows a little more stretch to prevent damage to the cable. 

I did notice that when the backbone is stretched to the max, the iPad Mini 6 just baaaarely fits if you "flex" one side back just enough to pop the iPad in. I would imagine doing this repeatedly will cause some damage to the backbone. I suggest maybe adding a tooth or two more to be able to get that little tiny bit of stretch extra to fit. Not sure how far the springs allow the backbone to stretch before they fully unravel but This is worth a try. I had a little strip of toolbox foam left over from doing some tool cutouts. I tucked this behind the iPad to give the backbone a little more support. Not sure if this is entirely necessary but if it prolongs the life post-modification, it is worth it. 

All-in-all I am happy as now I have a Playstation Portal but better. 

![image](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/9896716/c9356b77-ba5a-40c8-a39c-46632b1ba146)

**Comment by mattchinnock** [comment]
@DRA6N could you provide the source of the longer ribbon cables? Thanks!

**Comment by jonochocki** [comment]
Love to see it completed @DRA6N. Thanks for your insights and contributions in the reddit thread as well. Really appreciate the feedback. For future reference, a potential solution would be to print two of the "Top" pieces to add that extra 1 1/2 teeth needed (only if your ribbon cable config can support it). Other than that, it looks great! Thanks for sharing.

**Comment by jonochocki** [comment]
Love to see it completed @DRA6N. Thanks for your insights and contributions in the reddit thread as well. Really appreciate the feedback. For future reference, a potential solution would be to print two of the "Top" pieces to add that extra 1 1/2 teeth needed (only if your ribbon cable config can support it). Other than that, it looks great! Thanks for sharing.
