### ISSUE TITLE
Magnetic support adapter

### ISSUE THREAD

**Issue by agentx17** [itsjonlebron/Backbone-One-iPad-Mini-Upgrade#4]
I have not tinkered enough with designing my own pieces yet, but I feel like the included support inserts are too large for a iPad mini. Like there is too much wiggle room. Are you having issue with that?

**Comment by jonochocki** [comment]
Personally, I have not run into any issues daily playing the mod. Im curious where you suggest the supports are too large (because others have stated in the past the supports are not enough/too short). Let me know. Im happy to help problem solve.
