### ISSUE TITLE
Any success story with first gen BackBone One?

### ISSUE THREAD

**Issue by ikir83** [itsjonlebron/Backbone-One-iPad-Mini-Upgrade#6]
Hi all! Love how clear is this guide! Congratulation to author.

Before proceeding I would know if someone had a success modding the fits gen (USB-C) with updated firmware to support iPhone/iPad with USB-C.

thanks

**Comment by ikir83** [comment]
NO! I can confirm now this mod doesn't work with BackBone USB-C fist gen. The flat cable is too short.

**Comment by jonochocki** [comment]
Thanks so much for updating here. I see it's been a while but did you by chance take any reference photos while you were opening up the first gen? Id like to update the guide to include your findings. Looking more and more like this mod is gen-two only.

**Comment by ikir83** [comment]
I was shooting a video but sadly I've already deleted it, sorry! It seemed to me it was almost the same as your instructions, simply the thing did not extended enough to put the mini inside.
