### ISSUE TITLE
Max width and fpc cable

### ISSUE THREAD

**Issue by reiluke** [itsjonlebron/Backbone-One-iPad-Mini-Upgrade#7]
After the mod whats the max width tablet can it accomodate?

The cable is fpc 18pin .5mm pitch already have a longer cable and want to do your mod instead of ugly tape

Thanks for sharing

**Comment by jonochocki** [comment]
Hey! It's been a while since your comment, but the max tablet I can accommodate with this mod is an iPad mini 6th gen. Device length is approx: 7-3/4" (about 160mm).
