### ISSUE TITLE
Installed the upgrade on Backbone One Black 2nd Gen but still a bit too short

### ISSUE THREAD

**Issue by lorenzo999** [itsjonlebron/Backbone-One-iPad-Mini-Upgrade#8]
At first I installed two bottom parts since my ribbon cables are the same lenght on left/right, but it didn't work and the additional extension was minimal.
![IMG_3115](https://github.com/user-attachments/assets/e50e8d80-6add-449e-829d-26e387a8025e)

So I installed top and bottom parts and the extension was larger but I still can't fit my iPad Mini, because after inserting the USB-C port in the iPad there is not enough space to put it in place. It's possible to slide the iPad in the Backbone controller, just can't plug the port.

![IMG_3119](https://github.com/user-attachments/assets/cf1e05ff-6806-4ce7-8cb6-9eb1f0f63e66)
![IMG_3116](https://github.com/user-attachments/assets/7f08ed2f-35cb-4cfb-8bef-36455feb7c84)
![IMG_3118](https://github.com/user-attachments/assets/61db76e9-3527-42a2-853d-9fec782d7e08)

**Comment by lorenzo999** [comment]
I did it!

I had to file the little holes in the 3D printed supports as in the image below, probably even more than the image shown because I took this pic before doing the last few iterations.
![IMG_3123](https://github.com/user-attachments/assets/062d2ef5-c8be-419a-a908-c63fd9a8aeec)

After doing that (repeatedly) I gained the extra 3mm needed to complete the mod. GGs!
![IMG_3125](https://github.com/user-attachments/assets/4016bf29-7998-455a-aab1-aee74a9770f4)

**Comment by lorenzo999** [comment]
SIUUU

**Comment by jonochocki** [comment]
This looks great @lorenzo999! Thanks for sharing. Apologies I missed your initial thread, as I've been on vacation. Looks like you were able to make a few post-_post_-modifications. Looks great completed. I'll experiment with adjusting the supports as you've shared. Thanks again!

**Comment by lorenzo999** [comment]
Thanks a lot for sharing the project!
